ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"

urlpatterns = [
    path('addtocart/<int:i>',views.AddtoCart.as_view(),name="addtocart"),
    path('cartview',views.Cartview.as_view(),name="cartview"),
    path('cartdecrement/<int:i>',views.Cartdecrement.as_view(),name="cartdecrement"),
    path('cartremove/<int:i>',views.Cartremove.as_view(),name="cartremove"),
    path('checkout',views.Checkout.as_view(),name="checkout"),
    path('payment_success/<str:i>/',views.Payment_success.as_view(),name="success"),
    path('orders',views.Orders.as_view(),name="orders"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"

urlpatterns = [
    path('',views.SearchView.as_view(),name="search"),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.Categoryview.as_view(),name="categories"),
    path('products/<int:i>',views.Productview.as_view(),name="products"),
    path('productdetail/<int:i>',views.DetailView.as_view(),name="productdetail"),
    path('register',views.Register.as_view(),name="register"),
    path('login', views.Userlogin.as_view(), name="userlogin"),
    path('logout', views.Userlogout.as_view(), name="userlogout"),
    path('addcategory', views.AddCategoryView.as_view(), name="addcategory"),
    path('addproduct', views.AddProductView.as_view(), name="addproduct"),
    path('addstock/<int:i>', views.AddstockView.as_view(), name="addstock"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.product.price*self.quantity

from django.utils import timezone
class Order(models.Model):
    order_id = models.CharField(max_length=30,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(null=True)
    ordered_date = models.DateTimeField(auto_now=True)
    phone = models.IntegerField()
    address = models.TextField()
    is_ordered = models.BooleanField(default=False)
    payment_method = models.CharField(max_length=50)
    delivery_status = models.CharField(default="Pending")

    def __str__(self):
        return self.user.username


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="products")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.name

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/forms.py
from django import forms
from cart.models import Order
class OrderForm(forms.ModelForm):
    payment_choices=[('cod','COD'),('online','ONLINE')]
    payment_method=forms.ChoiceField(choices=payment_choices)
    class Meta:
        model=Order
        fields=['address','phone','payment_method']

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.views import View
from shop.models import Product
from cart.models import Cart
import razorpay
from cart.forms import OrderForm



class AddtoCart(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p)
            c.quantity+=1
            c.save()
        except:
            c=Cart.objects.create(user=u,product=p,quantity=1)
            c.save()
        return redirect('cart:cartview')


class Cartview(View):
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.product.price*i.quantity

        context={'cart':c,'total':total}
        return render(request,'cart.html',context)

class Cartdecrement(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p)
            if(c.quantity>1):
                c.quantity-=1
                c.save()
            else:
                c.delete()
        except:
            pass
        return redirect('cart:cartview')

class Cartremove(View):
    def get(self,request,i):
        p = Product.objects.get(id=i)
        u = request.user
        try:
            c = Cart.objects.get(user=u, product=p)

            c.delete()
        except:
            pass
        return redirect('cart:cartview')

def checkstock(c):
    for i in c:
        if i.product.stock<i.quantity:
            return False
    return True


from django.contrib import messages


# class Checkout(View):
#
#     def get(self, request):
#         user = request.user
#         cart_qs = Cart.objects.filter(user=user)
#         in_stock = checkstock(cart_qs)
#
#         # OUT OF STOCK -> only message
#         if not in_stock:
#             context = {
#                 "stock": False,
#                 "stock_message": "Currently items not available, cant place order. Please try again later!!!",
#             }
#             return render(request, "checkout.html", context)
#
#         # IN STOCK -> show form
#         form_instance = OrderForm()
#         context = {
#             "stock": True,
#             "form": form_instance,
#         }
#         return render(request, "checkout.html", context)
#
#     def post(self, request):
#         user = request.user
#         cart_qs = Cart.objects.filter(user=user)
#
#         # safety check again
#         in_stock = checkstock(cart_qs)
#         if not in_stock:
#             context = {
#                 "stock": False,
#                 "stock_message": "Currently items not available, cant place order. Please try again later!!!",
#             }
#             return render(request, "checkout.html", context)
#
#         form_instance = OrderForm(request.POST)
#
#         if form_instance.is_valid():
#             # ---- create order object ----
#             order = form_instance.save(commit=False)
#             order.user = user
#
#             total = 0
#             for item in cart_qs:
#                 total += item.product.price * item.quantity
#
#             order.amount = total   # make sure your Order model has amount
#             order.save()
#             print("Order saved with id:", order.id)
#
#             # ---- payment handling ----
#             # IMPORTANT: use the same value as in your form choices
#             # if you used ('online', 'ONLINE'), the value is 'online' (lowercase)
#             if order.payment_method == "online":
#                 print("Payment method = online, creating Razorpay order")
#                 client = razorpay.Client(auth=("rzp_test_RfE1mblAOkoa3l", "xA3Wi17XvtuWrIviVYaOth2Z"))
#                 response_payment = client.order.create(dict(
#                     amount = total * 100,   # in paise
#                     currency = "INR",
#                     payment_capture = 1
#                 ))
#                 print("response_payment:", response_payment)
#
#                 return render(
#                     request,
#                     "payment.html",
#                     {"order": order, "payment": response_payment},
#                 )
#
#             # COD branch
#             print("Payment method = COD, no Razorpay")
#             messages.success(request, "Order placed successfully with Cash on Delivery.")
#             return render(request, "payment.html", {"order": order})
#
#         # ---- form not valid ----
#         print("Form errors:", form_instance.errors)
#         messages.error(request, "Please correct the errors below.")
#         return render(
#             request,
#             "checkout.html",
#             {"form": form_instance, "stock": True},
      #  )
import uuid
class Checkout(View):
    def post(self,request):
        form_instance=OrderForm(request.POST)
        if form_instance.is_valid():
            o=form_instance.save(commit=False)

            u = request.user
            o.user=u

            c = Cart.objects.filter(user=u)
            total=0
            for i in c:
                total+=i.product.price*i.quantity
            o.amount=total
            o.save()
            print("order saved with id:",o.id)

            if(o.payment_method=="online"):
                #razorpay client connection
                client=razorpay.Client(auth=('rzp_test_RfE1mblAOkoa3l','xA3Wi17XvtuWrIviVYaOth2Z'))
                print(client)
                #place order
                response_payment=client.order.create(dict(amount=total*100,currency='INR'))
                print(response_payment)
                id=response_payment['id']
                o.order_id=id
                o.save()
                context={'payment':response_payment}
                return render(request,'payment.html',context)
            else:
                # order
                o.is_ordered = True
                uid=uuid.uuid4().hex[:14]
                id='order_COD'+uid
                o.order_id=id
                o.save()
                for i in c:
                    items = OrderItem.objects.create(order=o, product=i.product, quantity=i.quantity)
                    items.save()
                    items.product.stock -= items.quantity
                    items.product.save()

                # cart deletion
                c.delete()
                return render(request,'payment.html',)


    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        in_stock=checkstock(c)
        if not in_stock:
            context={"stock":False,"stock_message":"Currently items not available,cant place order,Please try again later!!!"}
            return render(request,"checkout.html",context)

        form_instance=OrderForm()
        context={'form':form_instance, 'stock':True,}
        return render(request,'checkout.html',context)


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib.auth import login
from cart.models import Order,OrderItem
@method_decorator(csrf_exempt,name="dispatch")
class Payment_success(View):


    def post(self,request,i):
        u=User.objects.get(username=i)
        login(request,u)
        response=request.POST
        print(response)
        id=response['razorpay_order_id']
        print(id)

        #order
        order=Order.objects.get(order_id=id)
        order.is_ordered=True
        order.save()

        #order_items
        c=Cart.objects.filter(user=u)
        for i in c:
            o=OrderItem.objects.create(order=order,product=i.product,quantity=i.quantity)
            o.save()
            o.product.stock-=o.quantity
            o.product.save()

        #cart deletion
        c.delete()
        return render(request,'payment_success.html')


class Orders(View):
    def get(self,request):
        u=request.user
        o=Order.objects.filter(user=u,is_ordered=True)
        context={'orders':o}
        return render(request,'orders.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from django.views import View

from shop.models import Product
from django.db.models import Q


class SearchView(View):
    def get(self,request):
        query = request.GET.get('q')
        print(query)
        if query:
            p = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(price__icontains=query))

            context = {'products': p}

        return render(request, 'search.html', context)

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Add Categories</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container w-50 p-5 border border-2 shadow mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class="mb-3">
            <input type="submit" class="btn btn-light">
        </div>
    </form>
</div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Update Stock</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container w-50 p-5 border border-2 shadow mt-5">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <div class="mb-3">
            <input type="submit" class="btn btn-light">
        </div>
    </form>
</div>
{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->
    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Unit Price</th>
                                    <th>Quantity</th>
                                    <th>SubTotal</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in cart %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{i.product.image.url}}" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
									{{i.product.name}}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>{{i.product.price}}</p>
                                    </td>
                                    <td class="quantity-box"><p>{{i.quantity}}</p></td>
                                    <td class="total-pr">
                                        <p>{{i.subtotal}}</p>
                                    </td>
                                    <td class="remove-pr">
                                        {% if i.product.stock > 0 %}
                                        <a href="{% url 'cart:addtocart' i.product.id %}">
									<i class="fa-solid fa-plus"></i>
								</a>
                                         <a href="{% url 'cart:cartdecrement' i.product.id %}">
									<i class="fa-solid fa-minus"></i>
								</a>
                                        <a href="{% url 'cart:cartremove' i.product.id %}">
									<i class="fas fa-times"></i>
								</a>
                                        {% else %}
                                        <a href="{% url 'cart:cartdecrement' i.product.id %}">
									<i class="fa-solid fa-minus"></i>
								</a>
                                        <a href="{% url 'cart:cartremove' i.product.id %}">
									<i class="fas fa-times"></i>
								</a>
                                        {% endif %}
                                    </td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <div class="d-flex">
                            <h4>Total</h4>
                            <div class="ml-auto font-weight-bold"> {{total}}</div>
                        </div>

                        <div class="d-flex">
                            <h4>Shipping Cost</h4>
                            <div class="ml-auto font-weight-bold"> Free </div>
                        </div>
                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Grand Total</h5>
                            <div class="ml-auto h5">{{total}}</div>
                        </div>
                        <hr> </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
    <!-- End Cart -->
{% endblock %}

ecommerce/templates/categories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
 <!-- Start Slider -->
    <div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="{% static 'images/banner-01.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-02.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-03.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>
    <!-- End Slider -->
 <!-- Start Products  -->
    <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1 class="mb-4">Our Collections</h1>
                        <p style="text-align:justify; line-height:2.5;">Lorem Ipsum is simply dummy text of the printing and
                            typesetting industry. Lorem Ipsum has been the industry's standard
                            dummy text ever since the 1500s, when an unknown printer took a galley of
                            type and scrambled it to make a type specimen book. It has survived not
                            only five centuries, but also the
                            leap into electronic typesetting, remaining essentially unchanged.  Lorem ipsum dolor sit amet, consectetur adipiscing
                            elit. Sed sit amet lacus enim.</p>
                    </div>
                </div>
            </div>
 <div class="categories-shop">
        <div class="container">
            <div class="row">
                {% for i in categories %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img class="" src="{{i.image.url}}" alt="" height="300px" width="100%" />
                        <a class="btn hvr-hover" href="{% url 'shop:products' i.id %}">{{i.name}}</a>
                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </div>
        </div>
    </div>
    <!-- End Categories -->
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Login</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div class="container w-50 p-5 border border-2 shadow mt-5">
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <div class="mb-3">
            <input type="submit" class="btn btn-light">
        </div>
    </form>
</div>
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

<div class="container mt-5 p-5 text-center w-50">
    {% if payment %}
<form action="{% url 'cart:success' user.username %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_RfE1mblAOkoa3l"
    data-amount="{{payment.amount}}"
    data-currency="INR"
    data-order_id="{{payment.id}}"
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{user.username}}"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#gray"

></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
{% else %}
<h1>Your Order is Placed Successfully</h1>
    {% endif %}
</div>
{% endblock %}

ecommerce/templates/productdetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Product Details</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">ABOUT US</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->

    <!-- Start About Page  -->
    <div class="about-box-main">
        <div class="container">
            <div class="row">
				<div class="col-lg-6">
                    <div class="banner-frame"> <img class="img-fluid" src="{{product.image.url}}" alt="" />
                    </div>
                </div>
                <div class="col-lg-6">
                    <h2 class="noo-sh-title-top mt-5">{{product.name}}</h2>
                    <h4 class="mt-3">Price:<b>Rs{{product.price}}</b></h4>
                    <h4 class="mt-2">{% if product.stock > 0 %} Currently <b>{{product.stock}}</b> items available {% endif %}</h4>
                    <h3 class="mt-2"><b>Short Description</b></h3>
                    <p style="text-align">{{product.description}}</p>

                    {% if user.is_superuser == True %}
                            <a class="btn hvr-hover" href="{% url 'shop:addstock' product.id %}">Addstock</a>
                    {% else %}
                            {% if product.stock > 0 %}
                                <a class="btn hvr-hover" href="{% url 'cart:addtocart' product.id %}">Add to Cart</a>
                            {% else %}
                                <h3>Out of Stock</h3>
                            {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <img src="{{category.image.url}}" height="400px" width="100%">
</div>
<!-- Start Products  -->
    <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{category.name}}</h1>
                        <p>{{category.description}}</p>
                    </div>
                </div>
            </div>


            <div class="row special-list">
                {% for j in category.products.all %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">

                            <img src="{{j.image.url}}" class="img-fluid" alt="Image">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' j.id %}">Details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{j.name}}</h4>
                            <h5> {{j.price}}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
    <!-- End Products  -->
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% block content %}
<div class="products-box">
        <div class="container">

            {% if products %}
            <div class="row special-list">
                {% for j in products %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">

                            <img src="{{j.image.url}}" class="img-fluid" alt="Image">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' j.id %}">Details</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{j.name}}</h4>
                            <h5> {{j.price}}</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                    <h2 class="text-danger fw-bold text-center">No Results Found</h2>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}